'use client';
import {useState} from 'react';
import reports from '@/public/news-review.json';

export default function Updates(){
 const [onlyChanges,setOnlyChanges]=useState(true),[query,setQuery]=useState('');
 const items=reports.items.filter(r=>(!onlyChanges||r.possibleChange)&&r.title.toLowerCase().includes(query.toLowerCase()));
 return <main className="updates-page"><a href="/">← Back to the map</a><h1>Source reports</h1><p>Newly collected headlines from local reporting. These can include existing places, closures and locations outside SF. Only reviewed opening evidence goes onto the map.</p><p className="updates-meta">Collected {new Date(reports.generatedAt).toLocaleDateString('en-US')} · {reports.items.length} retained reports</p><div className="updates-controls"><input aria-label="Search source reports" placeholder="Search headlines" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={onlyChanges} onChange={e=>setOnlyChanges(e.target.checked)}/> Possible openings and changes</label></div><p>{items.length} reports · headline matching is a discovery aid, not verification.</p><section aria-label="Source reports">{items.map(r=><article key={r.id} className="updates-card"><small>{r.sourceName} · {r.publishedAt?new Date(r.publishedAt).toLocaleDateString('en-US'):'Publication date unavailable'}</small><h2><a href={r.url} target="_blank" rel="noreferrer">{r.title} ↗</a></h2><span>{r.review.status==='added'?'Opening evidence reviewed and added to the map':'Needs review'}</span></article>)}</section>{items.length===0&&<p>No matching reports. Try a broader search or show all headlines.</p>}<footer><h2>Feed coverage</h2>{reports.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a>: {s.records} entries on the last fetch. {s.scope}</p>)}<a href="/news-review.json">Download collected headlines</a></footer></main>;
}
